// <auto-generated />
namespace BoardGamesRankingTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Plye : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Plye));
        
        string IMigrationMetadata.Id
        {
            get { return "202011120838360_Plye"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
